name: widget_book_widget_generator
description: Generate your widgetbook components by annotating your widgets.
version: 1.2.1
homepage: https://github.com/jorre127/widget_book_generator
repository: https://github.com/jorre127/widget_book_generator
issue_tracker: https://github.com/jorre127/widget_book_generator/issues

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  analyzer: ">=7.7.1 <10.0.0"
  build: ">=4.0.0 <5.0.0"
  code_builder: ">=4.11.0 <5.0.0"
  dart_style: ">=3.0.0 <4.0.0"
  flutter:
    sdk: flutter
  glob: ">=2.1.3 <3.0.0"
  source_gen: ">=3.1.0 <5.0.0"
  widget_book_widget_generator_annotations:
    path: ../widget_book_widget_generator_annotations
  widgetbook_annotation: ">=3.9.0 <4.0.0"
  widgetbook_generator: ">=3.16.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=6.0.0 <7.0.0"

# Comment before publishing
dependency_overrides:
  widget_book_widget_generator_annotations: 
    path: ../widget_book_widget_generator_annotations

flutter:
  uses-material-design: true
