builders:
  widget_book_widget_config_builder:
    import: "package:widget_book_generator/builder.dart"
    builder_factories: ["widgetBookWidgetConfigBuilder"]
    build_extensions: {".dart": [".widgetconfig.json"]}
    runs_before: ["widget_book_widget_builder"]
    auto_apply: dependents
    build_to: cache
  
  widget_book_widget_builder:
    import: "package:widget_book_generator/builder.dart"
    builder_factories: ["widgetBookWidgetBuilder"]
    build_extensions: {".dart": [".usecases.dart"]}
    auto_apply: dependents
    build_to: source