name: widget_book_generator
description: Generate your widgetbook components by annotating your widgets.
version: 1.0.0
homepage: https://github.com/jorre127/widget_book_generator
repository: https://github.com/jorre127/widget_book_generator
issue_tracker: https://github.com/jorre127/widget_book_generator/issues

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  analyzer: ^6.2.0
  build: ^2.4.1
  code_builder: ^4.7.0
  flutter:
    sdk: flutter
  source_gen: ^1.4.0
  widget_book_generator_annotations: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Comment before publishing
dependency_overrides:
  widget_book_generator_annotations: 
    path: ../widget_book_generator_annotations

flutter:
  uses-material-design: true
