name: widget_book_generator_annotations
description: Generate your widgetbook components by annotating your widgets.
version: 1.0.0
homepage: https://github.com/jorre127/widget_book_generator
repository: https://github.com/jorre127/widget_book_generator
issue_tracker: https://github.com/jorre127/widget_book_generator/issues

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
